### ISSUE TITLE
Missing instructions to run it

### ISSUE THREAD

**Issue by jerkan** [D-L-M/spritengine#1]
I tried to run it but I couldn't make it work.

It says 'cannot find package "github.com/D-L-M/spritengine"

**Comment by D-L-M** [comment]
Thanks for your interest in the project! Unfortunately since I wrote this proof-of-concept a number of things have changed that may make it difficult to run, including some third-party dependencies the last time I tried it out.

As this was only ever intended as a learning project for myself, it is not actively maintained. You may wish to check out https://github.com/faiface/pixel for a more fully featured project.
